//@ts-nocheck
export const catalogueCategories = [
    {
        id: 'corporate-uniforms',
        label: 'Corporate Uniforms',
        path: '/catalogue/corporate-uniforms',
        image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/46938c7e2_generated_image.png',
        description: 'Elevate your team\'s professional image with premium, bespoke corporate uniforms designed exclusively for your business. From blazers to polos, we craft workwear that reflects your brand identity.',
        subcategories: [
            { name: 'Custom Blazers & Suits with Logo', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/fb9594bd0_generated_image.png', desc: 'Impeccably tailored blazers and suits with precision logo embroidery that command respect in every boardroom.' },
            { name: 'Custom T-Shirts & Polo T-Shirts with Logo', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/4d2f86589_generated_image.png', desc: 'Premium cotton polos and t-shirts with crisp logo branding — perfect for casual corporate and frontline teams.' },
            { name: 'Custom Shirts', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/26232f694_generated_image.png', desc: 'Formal dress shirts crafted for everyday professional wear with custom fabric options and brand embroidery.' },
            { name: 'Ladies Office Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/09164bfbf_generated_image.png', desc: 'Elegant and professional uniforms for women — designed for comfort, style, and a polished corporate identity.' },
            { name: 'Mens Office Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/a6c233426_generated_image.png', desc: 'Sharp, well-fitted office uniforms for men that blend modern tailoring with day-long comfort.' },
            { name: 'Custom Jackets & Hoodies', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/149afa39b_generated_image.png', desc: 'Branded fleece jackets and hoodies for team outings, events, and casual corporate environments.' },
            { name: 'Custom Caps', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/c518a8648_generated_image.png', desc: 'Custom embroidered caps in a variety of styles — structured, unstructured, snapback — for every team.' },
            { name: 'Custom Logo Bags', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/4adb075cf_generated_image.png', desc: 'Professional tote bags, laptop bags, and backpacks with company branding for a complete corporate look.' },
            { name: 'Hospital Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/d4b1b1b5c_generated_image.png', desc: 'Complete uniform solutions for hospitals and clinics — from doctors coats to nurse scrubs and patient wear.' },
            { name: 'Industrial Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/709d5d509_generated_image.png', desc: 'Durable and safety-compliant industrial workwear for factories, construction sites, and manufacturing units.' },
            { name: 'Hotel Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/6d8286f36_generated_image.png', desc: 'Sophisticated hotel uniforms for front desk staff, housekeeping, chefs, and service teams.' },
        ],
    },
    {
        id: 'hospital-uniforms',
        label: 'Hospital Uniforms',
        path: '/catalogue/hospital-uniforms',
        image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/d4b1b1b5c_generated_image.png',
        description: 'Precision-crafted healthcare uniforms that combine hygiene standards, comfort, and professional presentation. Trusted by hospitals, clinics, and healthcare chains across India.',
        subcategories: [
            { name: 'Doctors Coat', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/1d59c7349_generated_image.png', desc: 'Pristine white doctor coats crafted from premium anti-bacterial fabric with custom embroidery options.' },
            { name: 'Lab Coats', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/1d59c7349_generated_image.png', desc: 'Professional laboratory coats in durable, easy-care fabric for researchers, technicians, and clinical staff.' },
            { name: 'Patient Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/ed1808e4e_generated_image.png', desc: 'Comfortable and dignified patient gowns and hospital wear designed for ease of movement and care.' },
            { name: 'Scrub Suits', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/52ebd90db_generated_image.png', desc: 'Modern scrub suits for surgical teams and ward staff — available in multiple colour codes for department identification.' },
            { name: 'Nurse Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/2dc0c29f9_generated_image.png', desc: 'Functional and professional nurse uniforms with antimicrobial fabric and department-specific colour options.' },
            { name: 'Hospital Dress', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/d4b1b1b5c_generated_image.png', desc: 'Complete hospital dress solutions for all departments — designed for comfort during long shifts.' },
        ],
    },
    {
        id: 'industrial-uniforms',
        label: 'Industrial Uniforms',
        path: '/catalogue/industrial-uniforms',
        image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/709d5d509_generated_image.png',
        description: 'Built for the toughest environments. Our industrial workwear meets safety standards while keeping your workforce looking professional and brand-aligned on the factory floor.',
        subcategories: [
            { name: 'Safety Jackets', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/1b9fade4c_generated_image.png', desc: 'High-visibility safety jackets with reflective strips, meeting IS/EN safety standards for industrial environments.' },
            { name: 'Boiler Suits', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/d61024afb_generated_image.png', desc: 'Heavy-duty boiler suits and coveralls for full-body protection in industrial and maintenance settings.' },
            { name: 'Worker Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/709d5d509_generated_image.png', desc: 'Durable daily-wear worker uniforms in robust fabric with reinforced stitching for demanding work environments.' },
            { name: 'Factory Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/709d5d509_generated_image.png', desc: 'Scalable factory uniform programs with consistent quality, colour coding by department and bulk supply.' },
            { name: 'Industrial Work Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/1b9fade4c_generated_image.png', desc: 'Customised industrial workwear incorporating your brand colours, logo, and safety features.' },
            { name: 'Safety Shoes', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/709d5d509_generated_image.png', desc: 'Steel-toe and composite-toe safety footwear to complete a comprehensive industrial PPE uniform program.' },
        ],
    },
    {
        id: 'hotel-uniforms',
        label: 'Hotel Uniforms',
        path: '/catalogue/hotel-uniforms',
        image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/6d8286f36_generated_image.png',
        description: 'Where hospitality meets elegance. Our hotel uniforms are designed to reflect your brand\'s luxury, create a lasting first impression, and keep your team comfortable through demanding shifts.',
        subcategories: [
            { name: 'Chef Coats', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/a27fbecc0_generated_image.png', desc: 'Classic double-breasted chef coats in premium cotton — with custom piping, buttons, and logo embroidery.' },
            { name: 'Chef Hats', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/a27fbecc0_generated_image.png', desc: 'Traditional and modern chef hats and toques, crafted for comfort and a professional kitchen presentation.' },
            { name: 'Chef Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/a27fbecc0_generated_image.png', desc: 'Complete chef uniform sets — coat, trousers, apron, and hat — designed for the heat and pace of professional kitchens.' },
            { name: 'Waiter Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/2e14f7f38_generated_image.png', desc: 'Polished waiter and service staff uniforms in formal and smart-casual styles to match your restaurant\'s ambience.' },
        ],
    },
    {
        id: 'other-uniforms',
        label: 'Other Uniforms',
        path: '/catalogue/other-uniforms',
        image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/af3cdf47b_generated_image.png',
        description: 'Professional uniforms for every specialized role. From beauty advisors to security personnel, we design purpose-built workwear that communicates professionalism and brand identity.',
        subcategories: [
            { name: 'Beauty Advisor Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/af3cdf47b_generated_image.png', desc: 'Stylish, brand-aligned uniforms for beauty advisors and retail beauty staff at counters and showrooms.' },
            { name: 'Beauty Salon Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/af3cdf47b_generated_image.png', desc: 'Elegant salon aprons and full uniforms for stylists, spa therapists, and wellness professionals.' },
            { name: 'Housekeeping Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/ce5e22095_generated_image.png', desc: 'Practical and presentable housekeeping uniforms for hotels, hospitals, and corporate facilities.' },
            { name: 'Security Guard Uniforms', image: 'https://media.base44.com/images/public/69f8ca90c257810149d2b4e6/bb7a4e130_generated_image.png', desc: 'Authority-inspiring security guard uniforms with badge fittings, shoulder straps, and bulk customization.' },
        ],
    },
];
